// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ1Hib74n9A2Eyre478zc5UyCK0JCLT_E',
    appId: '1:693152287777:web:4b0bc785e2dffa867fa760',
    messagingSenderId: '693152287777',
    projectId: 'study-mate-01',
    authDomain: 'study-mate-01.firebaseapp.com',
    storageBucket: 'study-mate-01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoasiYIccG296_M-OM6Fhvz3DN9g7-dhA',
    appId: '1:693152287777:android:b5f1d2a101947f997fa760',
    messagingSenderId: '693152287777',
    projectId: 'study-mate-01',
    storageBucket: 'study-mate-01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9o9GmYhGRdBfAwgpmclaUiQJFEq7W2cU',
    appId: '1:693152287777:ios:7eeebd9f3ddaceeb7fa760',
    messagingSenderId: '693152287777',
    projectId: 'study-mate-01',
    storageBucket: 'study-mate-01.appspot.com',
    iosClientId: '693152287777-q4hmj3s9jnf3jo1cmsv48ou76qpelsfh.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9o9GmYhGRdBfAwgpmclaUiQJFEq7W2cU',
    appId: '1:693152287777:ios:7eeebd9f3ddaceeb7fa760',
    messagingSenderId: '693152287777',
    projectId: 'study-mate-01',
    storageBucket: 'study-mate-01.appspot.com',
    iosClientId: '693152287777-q4hmj3s9jnf3jo1cmsv48ou76qpelsfh.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyMate',
  );
}
